title: "Bamsanchaeg"
description: "밤산책"
lang: ko-KR
timezone: Asia/Seoul
url: "https://bamsanchaeg.github.io"
baseurl: ""
permalink: /log/:year/:month/:day/:title/
future: false

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - .github
  - CHANGELOG.md
  - CONTRIBUTING.md
  - README.md
  - PROJECT.md
  - ROADMAP.md
  - SECURITY.md
  - Gemfile
  - Gemfile.lock
  - docs
